CREATE TABLE IF NOT EXISTS _schema_migrations (
    id TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS manifest_scopes (
    scope_id TEXT PRIMARY KEY,
    path_prefix TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sources (id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS requirements (id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS resolutions (id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS rules (id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS edges (id TEXT PRIMARY KEY, from_id TEXT NOT NULL, to_id TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_edges_from_id ON edges(from_id);
CREATE INDEX IF NOT EXISTS idx_edges_to_id ON edges(to_id);
