[package]
name = "provenance-scanner"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
provenance-macros = { path = "../provenance-macros" }
provenance-core = { path = "../provenance-core" }
serde.workspace = true
walkdir.workspace = true

[dev-dependencies]
provenance-macros = { path = "../provenance-macros" }
tempfile.workspace = true
